const palette = {
  primary: '#007AFF', // Standard iOS Blue or Pear Blue
  secondary: '#5856D6',
  success: '#34C759',
  danger: '#FF3B30',
  warning: '#FF9500',
  info: '#5AC8FA',
  white: '#FFFFFF',
  black: '#000000',
  gray: {
    50: '#F9F9F9',
    100: '#F2F2F7',
    200: '#E5E5EA',
    300: '#D1D1D6',
    400: '#C7C7CC',
    500: '#AEAEB2',
    600: '#8E8E93',
    700: '#636366',
    800: '#48484A',
    900: '#2C2C2E',
    950: '#1C1C1E',
  },
}

export default {
  light: {
    primary: palette.primary,
    secondary: palette.secondary,
    background: palette.white,
    surface: palette.gray[50],
    surfaceSecondary: palette.gray[100],
    text: palette.black,
    textSecondary: palette.gray[600],
    border: palette.gray[200],
    tint: palette.primary,
    success: palette.success,
    danger: palette.danger,
    warning: palette.warning,
    tabIconDefault: palette.gray[400],
    tabIconSelected: palette.primary,
  },
  dark: {
    primary: palette.primary,
    secondary: palette.secondary,
    background: palette.black,
    surface: palette.gray[950],
    surfaceSecondary: palette.gray[900],
    text: palette.white,
    textSecondary: palette.gray[400],
    border: palette.gray[800],
    tint: palette.white,
    success: palette.success,
    danger: palette.danger,
    warning: palette.warning,
    tabIconDefault: palette.gray[600],
    tabIconSelected: palette.white,
  },
}
